"""Keep the n8n workflow in step with the repo, and deploy it to the local n8n.

    uv run python -m leadq.n8n sync [--check]   # embed prompt, schema and code in the JSON
    uv run python -m leadq.n8n deploy           # credentials + workflow into n8n, published

`sync` writes the generated constants (model, prompt, schema, tier ranges) plus
workflows/code/*.js into the workflow's Code nodes; `--check` fails when the committed
workflow is out of date (CI). `deploy` imports the credentials from .env (n8n encrypts
them; nothing is printed), fills in the Telegram chat id, imports and publishes the
workflow and restarts n8n so the production webhook is registered.
"""

import argparse
import json
import shlex
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

from leadq.config import Settings
from leadq.qualify import (
    EFFORT,
    MAX_TOKENS,
    MODEL,
    SOURCES,
    TIER_RANGES,
    output_schema,
    system_prompt,
)

ROOT = Path(__file__).resolve().parents[2]
WORKFLOW_FILE = ROOT / "workflows" / "lead-intake.json"
CODE_DIR = ROOT / "workflows" / "code"
WORKFLOW_ID = "leadqLeadIntake1"
CHAT_ID_PLACEHOLDER = "TELEGRAM_CHAT_ID"
END_OF_CONSTANTS = "// --- end of generated constants ---"

# Code node name -> its source file and the constants it uses
CODE_NODES = {
    "Build Claude request": (
        "build_request.js",
        ("MODEL", "MAX_TOKENS", "EFFORT", "SOURCES", "SYSTEM_PROMPT", "OUTPUT_SCHEMA"),
    ),
    "Parse qualification": ("parse_qualification.js", ("SOURCES", "TIER_RANGES")),
}

# Credential ids the workflow refers to; deploy creates them with these ids.
CREDENTIAL_IDS = {
    "webhook": "leadqWebhookAuth",
    "anthropic": "leadqAnthropicKy",
    "telegram": "leadqTelegramBot",
}


def constants() -> dict[str, object]:
    return {
        "MODEL": MODEL,
        "MAX_TOKENS": MAX_TOKENS,
        "EFFORT": EFFORT,
        "SOURCES": SOURCES,
        "SYSTEM_PROMPT": system_prompt(),
        "OUTPUT_SCHEMA": output_schema(),
        "TIER_RANGES": {tier: list(bounds) for tier, bounds in TIER_RANGES.items()},
    }


def node_code(node_name: str) -> str:
    """The jsCode for a Code node: generated constants, then the source file."""
    filename, names = CODE_NODES[node_name]
    values = constants()
    header = [
        "// Generated by `python -m leadq.n8n sync` from prompts/, schemas/ and",
        f"// workflows/code/{filename}. Edit those files, not this node.",
        *(f"const {name} = {json.dumps(values[name], ensure_ascii=False)};" for name in names),
        END_OF_CONSTANTS,
        "",
    ]
    source = (CODE_DIR / filename).read_text(encoding="utf-8")
    return "\n".join(header) + source


def load_workflow(path: Path = WORKFLOW_FILE) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def dump_workflow(workflow: dict) -> str:
    return json.dumps(workflow, ensure_ascii=False, indent=2) + "\n"


def synced(workflow: dict) -> dict:
    result = json.loads(json.dumps(workflow))
    by_name = {node["name"]: node for node in result["nodes"]}
    for name in CODE_NODES:
        by_name[name]["parameters"]["jsCode"] = node_code(name)
    return result


def sync(check: bool) -> int:
    current = WORKFLOW_FILE.read_text(encoding="utf-8")
    expected = dump_workflow(synced(json.loads(current)))
    if current == expected:
        print("workflow is in sync")
        return 0
    if check:
        print(f"{WORKFLOW_FILE.relative_to(ROOT)} is out of date: run `python -m leadq.n8n sync`")
        return 1
    WORKFLOW_FILE.write_text(expected, encoding="utf-8", newline="\n")
    print(f"updated {WORKFLOW_FILE.relative_to(ROOT)}")
    return 0


# --- deploy --------------------------------------------------------------------------


def credentials(settings: Settings) -> list[dict]:
    """n8n credentials from .env. The values never leave this process except into n8n."""
    missing = [
        name
        for name, value in (
            ("LEADQ_WEBHOOK_SECRET", settings.webhook_secret),
            ("LEADQ_ANTHROPIC_API_KEY", settings.anthropic_api_key),
        )
        if value is None
    ]
    if missing:
        raise SystemExit(f"Set {', '.join(missing)} in .env first.")
    result = [
        {
            "id": CREDENTIAL_IDS["webhook"],
            "name": "Lead webhook secret",
            "type": "httpHeaderAuth",
            "data": {
                "name": "X-Webhook-Secret",
                "value": settings.webhook_secret.get_secret_value(),
            },
        },
        {
            "id": CREDENTIAL_IDS["anthropic"],
            "name": "Anthropic API key",
            "type": "httpHeaderAuth",
            "data": {"name": "x-api-key", "value": settings.anthropic_api_key.get_secret_value()},
        },
    ]
    if settings.telegram_bot_token is not None:
        result.append(
            {
                "id": CREDENTIAL_IDS["telegram"],
                "name": "Telegram bot",
                "type": "telegramApi",
                "data": {"accessToken": settings.telegram_bot_token.get_secret_value()},
            }
        )
    return result


def rendered(workflow: dict, chat_id: int | None) -> dict:
    """The workflow as deployed: synced, with the real Telegram chat id."""
    result = synced(workflow)
    if chat_id is not None:
        for node in result["nodes"]:
            if node["parameters"].get("chatId") == CHAT_ID_PLACEHOLDER:
                node["parameters"]["chatId"] = str(chat_id)
    return result


def compose(settings: Settings, *args: str, stdin: str | None = None) -> str:
    command = [*shlex.split(settings.compose_command), *args]
    result = subprocess.run(
        command,
        cwd=ROOT,
        input=stdin,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if result.returncode != 0:
        # n8n's error output doesn't echo stdin, so secrets can't leak through it.
        raise SystemExit(f"`{' '.join(args[:4])}` failed:\n{result.stdout}\n{result.stderr}")
    return result.stdout


def import_via_stdin(settings: Settings, kind: str, payload: object) -> str:
    """Copy JSON into the container through stdin (never onto the host disk) and import it."""
    path = f"/tmp/leadq-{kind}.json"
    script = f"cat > {path} && n8n import:{kind} --input={path}; s=$?; rm -f {path}; exit $s"
    return compose(settings, "exec", "-T", "n8n", "sh", "-c", script, stdin=json.dumps(payload))


def wait_healthy(settings: Settings, timeout_s: float = 120) -> None:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(f"{settings.n8n_url}/healthz", timeout=5) as response:
                if response.status == 200:
                    return
        except OSError:
            pass
        time.sleep(3)
    raise SystemExit(f"n8n didn't become healthy at {settings.n8n_url} within {timeout_s:.0f} s")


def deploy() -> int:
    settings = Settings()
    creds = credentials(settings)
    if settings.telegram_bot_token is None or settings.telegram_chat_id is None:
        print(
            "note: LEADQ_TELEGRAM_BOT_TOKEN or LEADQ_TELEGRAM_CHAT_ID is not set; "
            "hot-lead alerts will fail until both are in .env"
        )
    workflow = rendered(load_workflow(), settings.telegram_chat_id)

    print(f"importing {len(creds)} credentials ({', '.join(c['name'] for c in creds)})")
    import_via_stdin(settings, "credentials", creds)
    print(f"importing workflow {workflow['name']!r}")
    import_via_stdin(settings, "workflow", [workflow])
    print("publishing")
    compose(settings, "exec", "-T", "n8n", "n8n", "publish:workflow", f"--id={WORKFLOW_ID}")
    print("restarting n8n to register the production webhook")
    compose(settings, "restart", "n8n")
    wait_healthy(settings)
    print(f"ready: POST {settings.webhook_url} with header X-Webhook-Secret")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sync_parser = sub.add_parser("sync", help="embed prompt, schema and code in the workflow")
    sync_parser.add_argument("--check", action="store_true", help="fail if out of date")
    sub.add_parser("deploy", help="import credentials and the workflow into n8n")
    args = parser.parse_args()
    if args.command == "sync":
        return sync(args.check)
    return deploy()


if __name__ == "__main__":
    sys.exit(main())
