"""Keep the n8n workflows in step with the repo, and deploy them to the local n8n.

    uv run python -m leadq.n8n sync [--check]   # embed prompt, schema and code in the JSON
    uv run python -m leadq.n8n deploy           # credentials + workflows into n8n, published

`sync` writes the generated constants (model, prompt, schema, tier ranges) plus
workflows/code/*.js into the workflows' Code nodes; `--check` fails when the committed
workflow is out of date (CI). `deploy` imports the credentials from .env (n8n encrypts
them; nothing is printed), fills in the Telegram chat id, the spreadsheet id and the
Google credentials the owner signed in with in the n8n UI (Google nodes stay disabled
until those exist), imports and publishes both workflows ("Error alert" and "Lead
intake") and restarts n8n so the production webhook is registered.
"""

import argparse
import json
import shlex
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

from leadq.config import Settings
from leadq.qualify import (
    EFFORT,
    MAX_TOKENS,
    MODEL,
    SOURCES,
    TIER_RANGES,
    output_schema,
    system_prompt,
)

ROOT = Path(__file__).resolve().parents[2]
WORKFLOW_FILE = ROOT / "workflows" / "lead-intake.json"
ERROR_WORKFLOW_FILE = ROOT / "workflows" / "error-alert.json"
# Import order: the error workflow first, so the id "Lead intake" names already exists.
WORKFLOW_FILES = (ERROR_WORKFLOW_FILE, WORKFLOW_FILE)
CODE_DIR = ROOT / "workflows" / "code"
WORKFLOW_ID = "leadqLeadIntake1"
ERROR_WORKFLOW_ID = "leadqErrorAlert1"
CHAT_ID_PLACEHOLDER = "TELEGRAM_CHAT_ID"
END_OF_CONSTANTS = "// --- end of generated constants ---"

# Code node name -> its source file and the constants it uses
CODE_NODES = {
    "Build Claude request": (
        "build_request.js",
        ("MODEL", "MAX_TOKENS", "EFFORT", "SOURCES", "SYSTEM_PROMPT", "OUTPUT_SCHEMA"),
    ),
    "Parse qualification": ("parse_qualification.js", ("SOURCES", "TIER_RANGES")),
    "Sheet row": ("sheet_row.js", ()),
    "Format alert": ("error_alert.js", ()),
}

SHEET_ID_PLACEHOLDER = "GOOGLE_SHEET_ID"
# Google credentials are created by the owner in the n8n UI (OAuth sign-in happens
# there); deploy finds them by type. Node name -> credential type.
GOOGLE_NODES = {
    "Log to Google Sheets": "googleSheetsOAuth2Api",
    "Draft reply in Gmail": "gmailOAuth2",
}

# Credential ids the workflow refers to; deploy creates them with these ids.
CREDENTIAL_IDS = {
    "webhook": "leadqWebhookAuth",
    "anthropic": "leadqAnthropicKy",
    "telegram": "leadqTelegramBot",
}


def constants() -> dict[str, object]:
    return {
        "MODEL": MODEL,
        "MAX_TOKENS": MAX_TOKENS,
        "EFFORT": EFFORT,
        "SOURCES": SOURCES,
        "SYSTEM_PROMPT": system_prompt(),
        "OUTPUT_SCHEMA": output_schema(),
        "TIER_RANGES": {tier: list(bounds) for tier, bounds in TIER_RANGES.items()},
    }


def node_code(node_name: str) -> str:
    """The jsCode for a Code node: generated constants, then the source file."""
    filename, names = CODE_NODES[node_name]
    values = constants()
    header = [
        "// Generated by `python -m leadq.n8n sync` from prompts/, schemas/ and",
        f"// workflows/code/{filename}. Edit those files, not this node.",
        *(f"const {name} = {json.dumps(values[name], ensure_ascii=False)};" for name in names),
        END_OF_CONSTANTS,
        "",
    ]
    source = (CODE_DIR / filename).read_text(encoding="utf-8")
    return "\n".join(header) + source


def load_workflow(path: Path = WORKFLOW_FILE) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def dump_workflow(workflow: dict) -> str:
    return json.dumps(workflow, ensure_ascii=False, indent=2) + "\n"


def synced(workflow: dict) -> dict:
    """The workflow with fresh code in each of its Code nodes listed in CODE_NODES."""
    result = json.loads(json.dumps(workflow))
    for node in result["nodes"]:
        if node["name"] in CODE_NODES:
            node["parameters"]["jsCode"] = node_code(node["name"])
    return result


def sync(check: bool) -> int:
    stale = []
    for path in WORKFLOW_FILES:
        current = path.read_text(encoding="utf-8")
        expected = dump_workflow(synced(json.loads(current)))
        if current == expected:
            continue
        stale.append(path)
        if check:
            print(f"{path.relative_to(ROOT)} is out of date: run `python -m leadq.n8n sync`")
        else:
            path.write_text(expected, encoding="utf-8", newline="\n")
            print(f"updated {path.relative_to(ROOT)}")
    if not stale:
        print("workflows are in sync")
    return 1 if check and stale else 0


# --- deploy --------------------------------------------------------------------------


def credentials(settings: Settings) -> list[dict]:
    """n8n credentials from .env. The values never leave this process except into n8n."""
    missing = [
        name
        for name, value in (
            ("LEADQ_WEBHOOK_SECRET", settings.webhook_secret),
            ("LEADQ_ANTHROPIC_API_KEY", settings.anthropic_api_key),
        )
        if value is None
    ]
    if missing:
        raise SystemExit(f"Set {', '.join(missing)} in .env first.")
    result = [
        {
            "id": CREDENTIAL_IDS["webhook"],
            "name": "Lead webhook secret",
            "type": "httpHeaderAuth",
            "data": {
                "name": "X-Webhook-Secret",
                "value": settings.webhook_secret.get_secret_value(),
            },
        },
        {
            "id": CREDENTIAL_IDS["anthropic"],
            "name": "Anthropic API key",
            "type": "httpHeaderAuth",
            "data": {"name": "x-api-key", "value": settings.anthropic_api_key.get_secret_value()},
        },
    ]
    if settings.telegram_bot_token is not None:
        result.append(
            {
                "id": CREDENTIAL_IDS["telegram"],
                "name": "Telegram bot",
                "type": "telegramApi",
                "data": {"accessToken": settings.telegram_bot_token.get_secret_value()},
            }
        )
    return result


def rendered(
    workflow: dict,
    chat_id: int | None,
    google_credentials: dict[str, tuple[str, str]] | None = None,
    sheet_id: str | None = None,
) -> tuple[dict, list[str]]:
    """The workflow as deployed, and the names of nodes left disabled.

    Fills in the Telegram chat id, the spreadsheet id and the ids of the owner's Google
    credentials (type -> (id, name)). Google nodes whose credential or spreadsheet isn't
    set up yet are disabled: n8n skips a disabled node, so the rest keeps working.
    """
    result = synced(workflow)
    google_credentials = google_credentials or {}
    disabled = []
    for node in result["nodes"]:
        params = node["parameters"]
        if chat_id is not None and params.get("chatId") == CHAT_ID_PLACEHOLDER:
            params["chatId"] = str(chat_id)
        if node["name"] in GOOGLE_NODES:
            credential_type = GOOGLE_NODES[node["name"]]
            found = google_credentials.get(credential_type)
            needs_sheet = params.get("documentId", {}).get("value") == SHEET_ID_PLACEHOLDER
            if found is None or (needs_sheet and not sheet_id):
                node["disabled"] = True
                disabled.append(node["name"])
                continue
            node["credentials"][credential_type] = {"id": found[0], "name": found[1]}
            if needs_sheet:
                params["documentId"]["value"] = sheet_id
    return result, disabled


def compose(settings: Settings, *args: str, stdin: str | None = None) -> str:
    command = [*shlex.split(settings.compose_command), *args]
    result = subprocess.run(
        command,
        cwd=ROOT,
        input=stdin,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if result.returncode != 0:
        # n8n's error output doesn't echo stdin, so secrets can't leak through it.
        raise SystemExit(f"`{' '.join(args[:4])}` failed:\n{result.stdout}\n{result.stderr}")
    return result.stdout


def import_via_stdin(settings: Settings, kind: str, payload: object) -> str:
    """Copy JSON into the container through stdin (never onto the host disk) and import it.

    The script has no `$`: through `wsl --`, the WSL shell would expand it first.
    """
    path = f"/tmp/leadq-{kind}.json"
    script = (
        f"cat > {path} && n8n import:{kind} --input={path} && rm -f {path} "
        f"|| {{ rm -f {path}; exit 1; }}"
    )
    return compose(settings, "exec", "-T", "n8n", "sh", "-c", script, stdin=json.dumps(payload))


def parse_credential_rows(output: str) -> dict[str, tuple[str, str]]:
    """psql `-tA -F ,` rows of `type,id,name`, oldest first -> type -> (id, name) of the newest."""
    found: dict[str, tuple[str, str]] = {}
    for line in output.splitlines():
        parts = line.strip().split(",", 2)
        if len(parts) == 3 and parts[0] in GOOGLE_NODES.values():
            found[parts[0]] = (parts[1], parts[2])
    return found


def google_credentials(settings: Settings) -> dict[str, tuple[str, str]]:
    """The Google credentials the owner created in the n8n UI: type -> (id, name)."""
    types = ", ".join(f"'{t}'" for t in GOOGLE_NODES.values())
    sql = (
        f"SELECT type, id, name FROM credentials_entity WHERE type IN ({types}) "
        'ORDER BY "updatedAt";'
    )
    output = compose(
        settings,
        "exec",
        "-T",
        "db",
        "psql",
        "-U",
        settings.postgres_user,
        "-d",
        settings.postgres_db,
        "-tA",
        "-F",
        ",",
        stdin=sql,
    )
    return parse_credential_rows(output)


def wait_healthy(settings: Settings, timeout_s: float = 120) -> None:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(f"{settings.n8n_url}/healthz", timeout=5) as response:
                if response.status == 200:
                    return
        except OSError:
            pass
        time.sleep(3)
    raise SystemExit(f"n8n didn't become healthy at {settings.n8n_url} within {timeout_s:.0f} s")


def deploy() -> int:
    settings = Settings()
    creds = credentials(settings)
    if settings.telegram_bot_token is None or settings.telegram_chat_id is None:
        print(
            "note: LEADQ_TELEGRAM_BOT_TOKEN or LEADQ_TELEGRAM_CHAT_ID is not set; "
            "hot-lead alerts will fail until both are in .env"
        )
    google = google_credentials(settings)
    workflows, disabled = [], []
    for path in WORKFLOW_FILES:
        workflow, off = rendered(
            load_workflow(path), settings.telegram_chat_id, google, settings.google_sheet_id
        )
        workflows.append(workflow)
        disabled += off
    for name in disabled:
        reason = (
            f"no {GOOGLE_NODES[name]} credential in n8n"
            if GOOGLE_NODES[name] not in google
            else "LEADQ_GOOGLE_SHEET_ID is not set"
        )
        print(f"note: '{name}' stays disabled: {reason} (docs/setup-credentials.md)")

    print(f"importing {len(creds)} credentials ({', '.join(c['name'] for c in creds)})")
    import_via_stdin(settings, "credentials", creds)
    print(f"importing workflows {', '.join(repr(w['name']) for w in workflows)}")
    import_via_stdin(settings, "workflow", workflows)
    # Both are published: n8n 2.41 refuses to run an unpublished error workflow
    # ("is not active and cannot be executed"), although its docs say it needn't be.
    for workflow in workflows:
        print(f"publishing {workflow['name']!r}")
        compose(settings, "exec", "-T", "n8n", "n8n", "publish:workflow", f"--id={workflow['id']}")
    print("restarting n8n to register the production webhook")
    compose(settings, "restart", "n8n")
    wait_healthy(settings)
    print(f"ready: POST {settings.webhook_url} with header X-Webhook-Secret")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sync_parser = sub.add_parser("sync", help="embed prompt, schema and code in the workflows")
    sync_parser.add_argument("--check", action="store_true", help="fail if out of date")
    sub.add_parser("deploy", help="import credentials and the workflow into n8n")
    args = parser.parse_args()
    if args.command == "sync":
        return sync(args.check)
    return deploy()


if __name__ == "__main__":
    sys.exit(main())
